version: 2

sources:
  - name: dbt_unit_testing
    tables:
      - name: covid19_stg
        columns:
          - name: day
          - name: country_id
          - name: payload
      - name: covid19_country_stg
        columns:
          - name: country_id
          - name: country_name